"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['CopeTimer.py']
DATA_FILES = [('sounds', ['sounds/ring.wav'])]
OPTIONS = {'iconfile': '/Users/nathanthai/Documents/coding/python/TIMER/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
